from . import test_angle
from . import test_aruco
from . import test_cam
from . import test_main
from . import test_old_servo
from . import test_random
from . import test_scan
from . import test_sensor
from . import test_servo_pwm
from . import test_servo 
from . import test_spin_speed
from . import test_travel
from . import test_turn_angle
from . import test_turn
from . import test 